### PR TITLE
Add focus_next_visible.py example

### PR DESCRIPTION
**Pull request by Anon1234**

### CODE REVIEW

**Comment by acrisci** [comment]
Can you use dashes instead of underscores in the file name to make it consistent with the other examples?

**Comment by Anon1234** [comment]
Done.

**Comment by acrisci** [comment]
It should fail nicely if `xprop` is not found with a message to install it. Maybe check `check_output` for 127 and print the message there. Also, the dependency should be documented somewhere.

**Comment by Anon1234** [comment]
Done. Is there anything else to improve?

**Comment by acrisci** [comment]
Seems to work ok.

Thanks for the example :+1: .

**Pull request merged**
