### PR TITLE
Added title attribute to Con objects

### PR DESCRIPTION
**Pull request by alkim0**
Wasn't being set before.

### CODE REVIEW

**Comment by acrisci** [comment]
When is this ever different from `name`?

**Comment by acrisci** [comment]
Ok that seems reasonable.

Can you make the property `window_title` to be consistent with the rest of the window properties?

**Comment by alkim0** [comment]
Done.

Note that i3 uses `title` (e.g., `[title="mutt"]`) in its pattern matching as opposed to `window_title`.

**Comment by acrisci** [comment]
That is unfortunate, but we're inconsistent either way, and since it's a property, I'd rather go with being consistent with the properties as the ipc gives them.

:+1:

**Pull request merged**
