### PR TITLE
Make socket.recv() robust against interruptions

### PR DESCRIPTION
**Pull request by pb-**
The recv() syscall is interrupted if, e.g., the process receives a
signal. With this PR, we try to recv() again if recv() was interrupted.
(This is the idiomatic way to deal with interruptions.)

### CODE REVIEW

**Comment by acrisci** [comment]
Can you give me some background on why you made this change? Under what conditions would recv() be interrupted?

**Comment by pb-** [comment]
Hi.

Sure, sorry about the terseness. Suppose my program looks like:

```
from signal import signal, SIGUSR1

import i3ipc


def handler(signal, frame):
    print('I can handle this')


signal(SIGUSR1, handler)

i3 = i3ipc.Connection()
i3.main()
```

When you send `SIGUSR1` to the process running this program (for example with `kill -USR1 <pid>`), it dies with:

```
I can handle this
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    i3.main()
  File "/tmp/env/local/lib/python2.7/site-packages/i3ipc.py", line 338, in main
    data, msg_type = self._ipc_recv(self.sub_socket)
  File "/tmp/env/local/lib/python2.7/site-packages/i3ipc.py", line 219, in _ipc_recv
    data = sock.recv(14)
socket.error: [Errno 4] Interrupted system call
```

With this PR, you can handle signals and i3ipc will resume the interrupted system call after you are done with the handling.

Does that make sense?

Paul

**Comment by acrisci** [comment]
This works just fine in python 3.5.1, so this must be a python2 compat change.

**Comment by acrisci** [comment]
http://stackoverflow.com/questions/16094618/python-socket-recv-and-signals

http://bugs.python.org/issue9867

**Comment by acrisci** [comment]
Tested and the change fixes the issue with python2 :+1:

**Pull request merged**
